version: '3'
services:
  web:
   image: nginx:latest
   ports:
   - "80:80"
   - "443:443"
   volumes:
   - ./site.conf:/etc/nginx/conf.d/site.conf
   - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx.crt
   - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx.key
   links:
   - app
  app:
    build: .
    ports:
     - "3000:3000"
